<a href="https://colab.research.google.com/github/hamsain/learning-tensorflow/blob/main/mengenal_tensor_menggunakan_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mengenal Konsep Tensor dengan library TensorFlow

di sini kita akan membuat berbagai bentuk tensor dengan menggunakan tensorflow:
1. scalar
2. vector
3. matrix
4. tensor

In [ ]:
# mengimport library yang diperlukan
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
# 1. membuat Scalar dengan tf.constant()
# scalar adalah single number
my_scalar = tf.constant(5)
my_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
# 2. membuat vector
# vector adalah angka dengan arahan atau lebih dikenal array angka dengan 1 dimensi
my_vector = tf.constant([2,2])
my_vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [6]:
# 3. membuat matrix
# matrix adalah array angka dengan 2 dimensi
my_matrix = tf.constant([[1,2],
                         [3,4]])
my_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
# 4. membuat tensor
# tensor adalah array angka - angka dengan n dimensi
# array dengan 0 dimensi adalah scalar
# array dengan 1 dimensi adalah vector

my_tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
my_tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [8]:
# melihat dimensi masing bentuk tensor yang kita buat di atas dengan menggunakan sintaks .ndim
print("dimensi pada my_scalar adalah: ", my_scalar.ndim)
print("dimensi pada my_vector adalah: ", my_vector.ndim)
print("dimensi pada my_matrix adalah: ", my_matrix.ndim)
print("dimensi pada my_tensor adalah: ", my_tensor.ndim)

dimensi pada my_scalar adalah:  0
dimensi pada my_vector adalah:  1
dimensi pada my_matrix adalah:  2
dimensi pada my_tensor adalah:  3


In [ ]:
|