<a href="https://colab.research.google.com/github/hamsain/learning-tensorflow/blob/main/Tensors/02_cara_lain_membuat_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cara lain membuat tensor
1. membuat tensor berisikan angka 0 semua
2. membuat tensor berisikan angka 1 semuanya

In [1]:
# mengimport library
import tensorflow as tf

In [2]:
# membuat tensor 0 semuanya
lot_of_zeros = tf.zeros(shape=[2,3])
lot_of_zeros

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [3]:
# membuat tensor 1 semuanya
lot_of_ones = tf.ones(shape=[2,3])
lot_of_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>